### ISSUE TITLE
why import from '@vue/runtime-core' not from 'vue'

### ISSUE THREAD

**Issue by mesqueeb** [sethidden/vue-tsc-component-library-example#2]
Hi @sethidden I'm looking into how to best release my Vue components on npm, and this library has been very helpful.

I wonder. why do you do 
```js
import { PropType } from '@vue/runtime-core';
```
instead of 
```js
import { PropType } from 'vue';
```

thanks!

**Comment by sethidden** [comment]
Hi, this is probably because Volar auto-imported it from there and I didn't notice. Both of the examples you've mentioned are the same thing, but `vue` is more correct imo. I'll fix it later, thanks for reporting :)

**Comment by mesqueeb** [comment]
@sethidden aha! Phew! that's a relieve! : D I was panicking that there's something I was doing wrong by just importing from Vue : P
